services:
  db:
    image: postgres:14-alpine
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    env_file:
      - web.env
      - db.env
    build: .
    command: >
      sh -c "python /code/manage.py makemigrations &&
             python /code/manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 vpnchecker.wsgi:application"
    volumes:
      - .:/code
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - db.env
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - web

  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres_exporter
    env_file:
      - db.env
    ports:
      - "9187:9187"
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    env_file:
      - web.env
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  traefik:
    image: traefik:v2.9.6
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
  pgadmin-data:
  grafana-data:
  prometheus-data: