global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']